name: Quality pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  quality_api:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.head_ref }}-quality-api
      cancel-in-progress: true
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint
