name: Sauce Demo UI Playwright Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  sauce-demo-ui-playwright:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependancies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Sauce Demo UI Playwright Tests
        run: SAUCE_USERNAME=${{ secrets.SAUCE_USERNAME }} SAUCE_PASSWORD=${{ secrets.SAUCE_PASSWORD }}  npm run test:all

      - name: Upload Playwright Videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/

      - name: Upload Playwright Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/index.html

      - name: Prepare reports for GitHub Pages
        run: |
          mkdir -p public/playwright
          mkdir -p public/cypress
          cp -r playwright-report/* public/playwright/

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
